import { AppData } from './finance';

export const INITIAL_DATA: AppData = {
  balance: {
    current: 3458,
    income: 3814.25,
    expenses: 1700.5,
  },
  transactions: [
    {
      avatar: './assets/images/avatars/emma-richardson.jpg',
      name: 'Emma Richardson',
      category: 'General',
      date: '2024-08-19T14:23:11Z',
      amount: 75.5,
      recurring: false,
      id: 'UFdXZGXMkp8',
    },
    {
      avatar: './assets/images/avatars/savory-bites-bistro.jpg',
      name: 'Savory Bites Bistro',
      category: 'Dining Out',
      date: '2024-08-19T20:23:11Z',
      amount: -55.5,
      recurring: false,
      id: 'NSLL2Tv16pY',
    },
    {
      avatar: './assets/images/avatars/daniel-carter.jpg',
      name: 'Daniel Carter',
      category: 'General',
      date: '2024-08-18T09:45:32Z',
      amount: -42.3,
      recurring: false,
      id: '_xTGoBxDU74',
    },
    {
      avatar: './assets/images/avatars/sun-park.jpg',
      name: 'Sun Park',
      category: 'General',
      date: '2024-08-17T16:12:05Z',
      amount: 120,
      recurring: false,
      id: '78_CE-SXGxo',
    },
    {
      avatar: './assets/images/avatars/urban-services-hub.jpg',
      name: 'Urban Services Hub',
      category: 'General',
      date: '2024-08-17T21:08:09Z',
      amount: -65,
      recurring: false,
      id: 'bkc5gA_tHU8',
    },
    {
      avatar: './assets/images/avatars/liam-hughes.jpg',
      name: 'Liam Hughes',
      category: 'Groceries',
      date: '2024-08-15T18:20:33Z',
      amount: 65.75,
      recurring: false,
      id: 'xiFdYpdVvrE',
    },
    {
      avatar: './assets/images/avatars/lily-ramirez.jpg',
      name: 'Lily Ramirez',
      category: 'General',
      date: '2024-08-14T13:05:27Z',
      amount: 50,
      recurring: false,
      id: 'GppWVTDvFaU',
    },
    {
      avatar: './assets/images/avatars/ethan-clark.jpg',
      name: 'Ethan Clark',
      category: 'Dining Out',
      date: '2024-08-13T20:15:59Z',
      amount: -32.5,
      recurring: false,
      id: 'PjiDQhpzCl0',
    },
    {
      avatar: './assets/images/avatars/james-thompson.jpg',
      name: 'James Thompson',
      category: 'Entertainment',
      date: '2024-08-11T15:45:38Z',
      amount: -5,
      recurring: false,
      id: 'TPNSYYxtd_M',
    },
    {
      avatar: './assets/images/avatars/pixel-playground.jpg',
      name: 'Pixel Playground',
      category: 'Entertainment',
      date: '2024-08-11T18:45:38Z',
      amount: -10,
      recurring: true,
      id: 'MHQDdTaqbPQ',
    },
    {
      avatar: './assets/images/avatars/ella-phillips.jpg',
      name: 'Ella Phillips',
      category: 'Dining Out',
      date: '2024-08-10T19:22:51Z',
      amount: -45,
      recurring: false,
      id: 'zZsaVrMLD9Y',
    },
    {
      avatar: './assets/images/avatars/sofia-peterson.jpg',
      name: 'Sofia Peterson',
      category: 'Transportation',
      date: '2024-08-08T08:55:17Z',
      amount: -15,
      recurring: false,
      id: '787nKNUYupg',
    },
    {
      avatar: './assets/images/avatars/mason-martinez.jpg',
      name: 'Mason Martinez',
      category: 'Lifestyle',
      date: '2024-08-07T17:40:29Z',
      amount: -35.25,
      recurring: false,
      id: 'flMmfvPF2gc',
    },
    {
      avatar: './assets/images/avatars/green-plate-eatery.jpg',
      name: 'Green Plate Eatery',
      category: 'Groceries',
      date: '2024-08-06T08:25:44Z',
      amount: -78.5,
      recurring: false,
      id: 'NINaf0qpOZ8',
    },
    {
      avatar: './assets/images/avatars/sebastian-cook.jpg',
      name: 'Sebastian Cook',
      category: 'Transportation',
      date: '2024-08-06T10:05:44Z',
      amount: -22.5,
      recurring: false,
      id: 'qiMqwySdVKg',
    },
    {
      avatar: './assets/images/avatars/william-harris.jpg',
      name: 'William Harris',
      category: 'Personal Care',
      date: '2024-08-05T14:30:56Z',
      amount: -10,
      recurring: false,
      id: '6p1xzZoXvKQ',
    },
    {
      avatar: './assets/images/avatars/elevate-education.jpg',
      name: 'Elevate Education',
      category: 'Education',
      date: '2024-08-04T11:15:22Z',
      amount: -50,
      recurring: true,
      id: 'r8jvlQ-xc3g',
    },
    {
      avatar: './assets/images/avatars/serenity-spa-and-wellness.jpg',
      name: 'Serenity Spa & Wellness',
      category: 'Personal Care',
      date: '2024-08-03T14:00:37Z',
      amount: -30,
      recurring: true,
      id: 'U4iA4vHtEpQ',
    },
    {
      avatar: './assets/images/avatars/spark-electric-solutions.jpg',
      name: 'Spark Electric Solutions',
      category: 'Bills',
      date: '2024-08-02T09:25:11Z',
      amount: -100,
      recurring: true,
      id: 'WCMZ7ET1wyc',
    },
    {
      avatar: './assets/images/avatars/rina-sato.jpg',
      name: 'Rina Sato',
      category: 'Bills',
      date: '2024-08-02T13:31:11Z',
      amount: -50,
      recurring: false,
      id: 'X_mLSpdFPh8',
    },
    {
      avatar: './assets/images/avatars/swift-ride-share.jpg',
      name: 'Swift Ride Share',
      category: 'Transportation',
      date: '2024-08-01T18:40:33Z',
      amount: -18.75,
      recurring: false,
      id: 'w_E2iN_CaG8',
    },
    {
      avatar: './assets/images/avatars/aqua-flow-utilities.jpg',
      name: 'Aqua Flow Utilities',
      category: 'Bills',
      date: '2024-07-30T13:20:14Z',
      amount: -100,
      recurring: true,
      id: 'iabaPaabA6Y',
    },
    {
      avatar: './assets/images/avatars/ecofuel-energy.jpg',
      name: 'EcoFuel Energy',
      category: 'Bills',
      date: '2024-07-29T11:55:29Z',
      amount: -35,
      recurring: true,
      id: '8hFid1g19aM',
    },
    {
      avatar: './assets/images/avatars/yuna-kim.jpg',
      name: 'Yuna Kim',
      category: 'Dining Out',
      date: '2024-07-29T13:51:29Z',
      amount: -28.5,
      recurring: false,
      id: '2UCXSyQRC4s',
    },
    {
      avatar: './assets/images/avatars/flavor-fiesta.jpg',
      name: 'Flavor Fiesta',
      category: 'Dining Out',
      date: '2024-07-27T20:15:06Z',
      amount: -42.75,
      recurring: false,
      id: '8251tBhjAnE',
    },
    {
      avatar: './assets/images/avatars/harper-edwards.jpg',
      name: 'Harper Edwards',
      category: 'Shopping',
      date: '2024-07-26T09:43:23Z',
      amount: -89.99,
      recurring: false,
      id: 'I_0qnbx4FVg',
    },
    {
      avatar: './assets/images/avatars/buzz-marketing-group.jpg',
      name: 'Buzz Marketing Group',
      category: 'General',
      date: '2024-07-26T14:40:23Z',
      amount: 3358,
      recurring: false,
      id: 'xFv1-V7AeBo',
    },
    {
      avatar: './assets/images/avatars/technova-innovations.jpg',
      name: 'TechNova Innovations',
      category: 'Shopping',
      date: '2024-07-25T16:25:37Z',
      amount: -29.99,
      recurring: false,
      id: 'qrrX2XPN664',
    },
    {
      avatar: './assets/images/avatars/bytewise.jpg',
      name: 'ByteWise',
      category: 'Lifestyle',
      date: '2024-07-23T09:35:14Z',
      amount: -49.99,
      recurring: true,
      id: 'eLUnFDuLCOs',
    },
    {
      avatar: './assets/images/avatars/nimbus-data-storage.jpg',
      name: 'Nimbus Data Storage',
      category: 'Bills',
      date: '2024-07-21T10:05:42Z',
      amount: -9.99,
      recurring: true,
      id: 'd4H0KiIP9cw',
    },
    {
      avatar: './assets/images/avatars/emma-richardson.jpg',
      name: 'Emma Richardson',
      category: 'General',
      date: '2024-07-20T17:30:55Z',
      amount: -25,
      recurring: false,
      id: 'H0OWI_wfbW0',
    },
    {
      avatar: './assets/images/avatars/daniel-carter.jpg',
      name: 'Daniel Carter',
      category: 'General',
      date: '2024-07-19T12:45:09Z',
      amount: 50,
      recurring: false,
      id: 'rhOL6T7YYoU',
    },
  ],
  budgets: [
    { category: 'Entertainment', maximum: 50, theme: '#277c78', id: 'b1' },
    { category: 'Personal Care', maximum: 100, theme: '#626070', id: 'b2' },
    { category: 'Bills', maximum: 500, theme: '#82c9d7', id: 'b3' },
    { category: 'Dining Out', maximum: 250, theme: '#f2cdac', id: 'b4' },
  ],
  pots: [
    { name: 'Concert Ticket', target: 150, total: 110, theme: '#626070', id: 'p1' },
    { name: 'Gift', target: 150, total: 40, theme: '#82c9d7', id: 'p2' },
    { name: 'New Laptop', target: 1000, total: 10, theme: '#f2cdac', id: 'p3' },
    { name: 'Holiday', target: 1440, total: 531, theme: '#826cb0', id: 'p4' },
  ],
};
